using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IFME
{
    internal static partial class Fonts
    {
        internal static class fa
        {
            public static string glass { get { return $"{(char)0xf000}"; } }
            public static string music { get { return $"{(char)0xf001}"; } }
            public static string search { get { return $"{(char)0xf002}"; } }
            public static string envelope_o { get { return $"{(char)0xf003}"; } }
            public static string heart { get { return $"{(char)0xf004}"; } }
            public static string star { get { return $"{(char)0xf005}"; } }
            public static string star_o { get { return $"{(char)0xf006}"; } }
            public static string user { get { return $"{(char)0xf007}"; } }
            public static string film { get { return $"{(char)0xf008}"; } }
            public static string th_large { get { return $"{(char)0xf009}"; } }
            public static string th { get { return $"{(char)0xf00a}"; } }
            public static string th_list { get { return $"{(char)0xf00b}"; } }
            public static string check { get { return $"{(char)0xf00c}"; } }
            public static string remove { get { return $"{(char)0xf00d}"; } }
            public static string close { get { return $"{(char)0xf00d}"; } }
            public static string times { get { return $"{(char)0xf00d}"; } }
            public static string search_plus { get { return $"{(char)0xf00e}"; } }
            public static string search_minus { get { return $"{(char)0xf010}"; } }
            public static string power_off { get { return $"{(char)0xf011}"; } }
            public static string signal { get { return $"{(char)0xf012}"; } }
            public static string gear { get { return $"{(char)0xf013}"; } }
            public static string cog { get { return $"{(char)0xf013}"; } }
            public static string trash_o { get { return $"{(char)0xf014}"; } }
            public static string home { get { return $"{(char)0xf015}"; } }
            public static string file_o { get { return $"{(char)0xf016}"; } }
            public static string clock_o { get { return $"{(char)0xf017}"; } }
            public static string road { get { return $"{(char)0xf018}"; } }
            public static string download { get { return $"{(char)0xf019}"; } }
            public static string arrow_circle_o_down { get { return $"{(char)0xf01a}"; } }
            public static string arrow_circle_o_up { get { return $"{(char)0xf01b}"; } }
            public static string inbox { get { return $"{(char)0xf01c}"; } }
            public static string play_circle_o { get { return $"{(char)0xf01d}"; } }
            public static string rotate_right { get { return $"{(char)0xf01e}"; } }
            public static string repeat { get { return $"{(char)0xf01e}"; } }
            public static string refresh { get { return $"{(char)0xf021}"; } }
            public static string list_alt { get { return $"{(char)0xf022}"; } }
            public static string @lock { get { return $"{(char)0xf023}"; } }
            public static string flag { get { return $"{(char)0xf024}"; } }
            public static string headphones { get { return $"{(char)0xf025}"; } }
            public static string volume_off { get { return $"{(char)0xf026}"; } }
            public static string volume_down { get { return $"{(char)0xf027}"; } }
            public static string volume_up { get { return $"{(char)0xf028}"; } }
            public static string qrcode { get { return $"{(char)0xf029}"; } }
            public static string barcode { get { return $"{(char)0xf02a}"; } }
            public static string tag { get { return $"{(char)0xf02b}"; } }
            public static string tags { get { return $"{(char)0xf02c}"; } }
            public static string book { get { return $"{(char)0xf02d}"; } }
            public static string bookmark { get { return $"{(char)0xf02e}"; } }
            public static string print { get { return $"{(char)0xf02f}"; } }
            public static string camera { get { return $"{(char)0xf030}"; } }
            public static string font { get { return $"{(char)0xf031}"; } }
            public static string bold { get { return $"{(char)0xf032}"; } }
            public static string italic { get { return $"{(char)0xf033}"; } }
            public static string text_height { get { return $"{(char)0xf034}"; } }
            public static string text_width { get { return $"{(char)0xf035}"; } }
            public static string align_left { get { return $"{(char)0xf036}"; } }
            public static string align_center { get { return $"{(char)0xf037}"; } }
            public static string align_right { get { return $"{(char)0xf038}"; } }
            public static string align_justify { get { return $"{(char)0xf039}"; } }
            public static string list { get { return $"{(char)0xf03a}"; } }
            public static string dedent { get { return $"{(char)0xf03b}"; } }
            public static string outdent { get { return $"{(char)0xf03b}"; } }
            public static string indent { get { return $"{(char)0xf03c}"; } }
            public static string video_camera { get { return $"{(char)0xf03d}"; } }
            public static string photo { get { return $"{(char)0xf03e}"; } }
            public static string image { get { return $"{(char)0xf03e}"; } }
            public static string picture_o { get { return $"{(char)0xf03e}"; } }
            public static string pencil { get { return $"{(char)0xf040}"; } }
            public static string map_marker { get { return $"{(char)0xf041}"; } }
            public static string adjust { get { return $"{(char)0xf042}"; } }
            public static string tint { get { return $"{(char)0xf043}"; } }
            public static string edit { get { return $"{(char)0xf044}"; } }
            public static string pencil_square_o { get { return $"{(char)0xf044}"; } }
            public static string share_square_o { get { return $"{(char)0xf045}"; } }
            public static string check_square_o { get { return $"{(char)0xf046}"; } }
            public static string arrows { get { return $"{(char)0xf047}"; } }
            public static string step_backward { get { return $"{(char)0xf048}"; } }
            public static string fast_backward { get { return $"{(char)0xf049}"; } }
            public static string backward { get { return $"{(char)0xf04a}"; } }
            public static string play { get { return $"{(char)0xf04b}"; } }
            public static string pause { get { return $"{(char)0xf04c}"; } }
            public static string stop { get { return $"{(char)0xf04d}"; } }
            public static string forward { get { return $"{(char)0xf04e}"; } }
            public static string fast_forward { get { return $"{(char)0xf050}"; } }
            public static string step_forward { get { return $"{(char)0xf051}"; } }
            public static string eject { get { return $"{(char)0xf052}"; } }
            public static string chevron_left { get { return $"{(char)0xf053}"; } }
            public static string chevron_right { get { return $"{(char)0xf054}"; } }
            public static string plus_circle { get { return $"{(char)0xf055}"; } }
            public static string minus_circle { get { return $"{(char)0xf056}"; } }
            public static string times_circle { get { return $"{(char)0xf057}"; } }
            public static string check_circle { get { return $"{(char)0xf058}"; } }
            public static string question_circle { get { return $"{(char)0xf059}"; } }
            public static string info_circle { get { return $"{(char)0xf05a}"; } }
            public static string crosshairs { get { return $"{(char)0xf05b}"; } }
            public static string times_circle_o { get { return $"{(char)0xf05c}"; } }
            public static string check_circle_o { get { return $"{(char)0xf05d}"; } }
            public static string ban { get { return $"{(char)0xf05e}"; } }
            public static string arrow_left { get { return $"{(char)0xf060}"; } }
            public static string arrow_right { get { return $"{(char)0xf061}"; } }
            public static string arrow_up { get { return $"{(char)0xf062}"; } }
            public static string arrow_down { get { return $"{(char)0xf063}"; } }
            public static string mail_forward { get { return $"{(char)0xf064}"; } }
            public static string share { get { return $"{(char)0xf064}"; } }
            public static string expand { get { return $"{(char)0xf065}"; } }
            public static string compress { get { return $"{(char)0xf066}"; } }
            public static string plus { get { return $"{(char)0xf067}"; } }
            public static string minus { get { return $"{(char)0xf068}"; } }
            public static string asterisk { get { return $"{(char)0xf069}"; } }
            public static string exclamation_circle { get { return $"{(char)0xf06a}"; } }
            public static string gift { get { return $"{(char)0xf06b}"; } }
            public static string leaf { get { return $"{(char)0xf06c}"; } }
            public static string fire { get { return $"{(char)0xf06d}"; } }
            public static string eye { get { return $"{(char)0xf06e}"; } }
            public static string eye_slash { get { return $"{(char)0xf070}"; } }
            public static string warning { get { return $"{(char)0xf071}"; } }
            public static string exclamation_triangle { get { return $"{(char)0xf071}"; } }
            public static string plane { get { return $"{(char)0xf072}"; } }
            public static string calendar { get { return $"{(char)0xf073}"; } }
            public static string random { get { return $"{(char)0xf074}"; } }
            public static string comment { get { return $"{(char)0xf075}"; } }
            public static string magnet { get { return $"{(char)0xf076}"; } }
            public static string chevron_up { get { return $"{(char)0xf077}"; } }
            public static string chevron_down { get { return $"{(char)0xf078}"; } }
            public static string retweet { get { return $"{(char)0xf079}"; } }
            public static string shopping_cart { get { return $"{(char)0xf07a}"; } }
            public static string folder { get { return $"{(char)0xf07b}"; } }
            public static string folder_open { get { return $"{(char)0xf07c}"; } }
            public static string arrows_v { get { return $"{(char)0xf07d}"; } }
            public static string arrows_h { get { return $"{(char)0xf07e}"; } }
            public static string bar_chart_o { get { return $"{(char)0xf080}"; } }
            public static string bar_chart { get { return $"{(char)0xf080}"; } }
            public static string twitter_square { get { return $"{(char)0xf081}"; } }
            public static string facebook_square { get { return $"{(char)0xf082}"; } }
            public static string camera_retro { get { return $"{(char)0xf083}"; } }
            public static string key { get { return $"{(char)0xf084}"; } }
            public static string gears { get { return $"{(char)0xf085}"; } }
            public static string cogs { get { return $"{(char)0xf085}"; } }
            public static string comments { get { return $"{(char)0xf086}"; } }
            public static string thumbs_o_up { get { return $"{(char)0xf087}"; } }
            public static string thumbs_o_down { get { return $"{(char)0xf088}"; } }
            public static string star_half { get { return $"{(char)0xf089}"; } }
            public static string heart_o { get { return $"{(char)0xf08a}"; } }
            public static string sign_out { get { return $"{(char)0xf08b}"; } }
            public static string linkedin_square { get { return $"{(char)0xf08c}"; } }
            public static string thumb_tack { get { return $"{(char)0xf08d}"; } }
            public static string external_link { get { return $"{(char)0xf08e}"; } }
            public static string sign_in { get { return $"{(char)0xf090}"; } }
            public static string trophy { get { return $"{(char)0xf091}"; } }
            public static string github_square { get { return $"{(char)0xf092}"; } }
            public static string upload { get { return $"{(char)0xf093}"; } }
            public static string lemon_o { get { return $"{(char)0xf094}"; } }
            public static string phone { get { return $"{(char)0xf095}"; } }
            public static string square_o { get { return $"{(char)0xf096}"; } }
            public static string bookmark_o { get { return $"{(char)0xf097}"; } }
            public static string phone_square { get { return $"{(char)0xf098}"; } }
            public static string twitter { get { return $"{(char)0xf099}"; } }
            public static string facebook_f { get { return $"{(char)0xf09a}"; } }
            public static string facebook { get { return $"{(char)0xf09a}"; } }
            public static string github { get { return $"{(char)0xf09b}"; } }
            public static string unlock { get { return $"{(char)0xf09c}"; } }
            public static string credit_card { get { return $"{(char)0xf09d}"; } }
            public static string feed { get { return $"{(char)0xf09e}"; } }
            public static string rss { get { return $"{(char)0xf09e}"; } }
            public static string hdd_o { get { return $"{(char)0xf0a0}"; } }
            public static string bullhorn { get { return $"{(char)0xf0a1}"; } }
            public static string bell { get { return $"{(char)0xf0f3}"; } }
            public static string certificate { get { return $"{(char)0xf0a3}"; } }
            public static string hand_o_right { get { return $"{(char)0xf0a4}"; } }
            public static string hand_o_left { get { return $"{(char)0xf0a5}"; } }
            public static string hand_o_up { get { return $"{(char)0xf0a6}"; } }
            public static string hand_o_down { get { return $"{(char)0xf0a7}"; } }
            public static string arrow_circle_left { get { return $"{(char)0xf0a8}"; } }
            public static string arrow_circle_right { get { return $"{(char)0xf0a9}"; } }
            public static string arrow_circle_up { get { return $"{(char)0xf0aa}"; } }
            public static string arrow_circle_down { get { return $"{(char)0xf0ab}"; } }
            public static string globe { get { return $"{(char)0xf0ac}"; } }
            public static string wrench { get { return $"{(char)0xf0ad}"; } }
            public static string tasks { get { return $"{(char)0xf0ae}"; } }
            public static string filter { get { return $"{(char)0xf0b0}"; } }
            public static string briefcase { get { return $"{(char)0xf0b1}"; } }
            public static string arrows_alt { get { return $"{(char)0xf0b2}"; } }
            public static string group { get { return $"{(char)0xf0c0}"; } }
            public static string users { get { return $"{(char)0xf0c0}"; } }
            public static string chain { get { return $"{(char)0xf0c1}"; } }
            public static string link { get { return $"{(char)0xf0c1}"; } }
            public static string cloud { get { return $"{(char)0xf0c2}"; } }
            public static string flask { get { return $"{(char)0xf0c3}"; } }
            public static string cut { get { return $"{(char)0xf0c4}"; } }
            public static string scissors { get { return $"{(char)0xf0c4}"; } }
            public static string copy { get { return $"{(char)0xf0c5}"; } }
            public static string files_o { get { return $"{(char)0xf0c5}"; } }
            public static string paperclip { get { return $"{(char)0xf0c6}"; } }
            public static string save { get { return $"{(char)0xf0c7}"; } }
            public static string floppy_o { get { return $"{(char)0xf0c7}"; } }
            public static string square { get { return $"{(char)0xf0c8}"; } }
            public static string navicon { get { return $"{(char)0xf0c9}"; } }
            public static string reorder { get { return $"{(char)0xf0c9}"; } }
            public static string bars { get { return $"{(char)0xf0c9}"; } }
            public static string list_ul { get { return $"{(char)0xf0ca}"; } }
            public static string list_ol { get { return $"{(char)0xf0cb}"; } }
            public static string strikethrough { get { return $"{(char)0xf0cc}"; } }
            public static string underline { get { return $"{(char)0xf0cd}"; } }
            public static string table { get { return $"{(char)0xf0ce}"; } }
            public static string magic { get { return $"{(char)0xf0d0}"; } }
            public static string truck { get { return $"{(char)0xf0d1}"; } }
            public static string pinterest { get { return $"{(char)0xf0d2}"; } }
            public static string pinterest_square { get { return $"{(char)0xf0d3}"; } }
            public static string google_plus_square { get { return $"{(char)0xf0d4}"; } }
            public static string google_plus { get { return $"{(char)0xf0d5}"; } }
            public static string money { get { return $"{(char)0xf0d6}"; } }
            public static string caret_down { get { return $"{(char)0xf0d7}"; } }
            public static string caret_up { get { return $"{(char)0xf0d8}"; } }
            public static string caret_left { get { return $"{(char)0xf0d9}"; } }
            public static string caret_right { get { return $"{(char)0xf0da}"; } }
            public static string columns { get { return $"{(char)0xf0db}"; } }
            public static string unsorted { get { return $"{(char)0xf0dc}"; } }
            public static string sort { get { return $"{(char)0xf0dc}"; } }
            public static string sort_down { get { return $"{(char)0xf0dd}"; } }
            public static string sort_desc { get { return $"{(char)0xf0dd}"; } }
            public static string sort_up { get { return $"{(char)0xf0de}"; } }
            public static string sort_asc { get { return $"{(char)0xf0de}"; } }
            public static string envelope { get { return $"{(char)0xf0e0}"; } }
            public static string linkedin { get { return $"{(char)0xf0e1}"; } }
            public static string rotate_left { get { return $"{(char)0xf0e2}"; } }
            public static string undo { get { return $"{(char)0xf0e2}"; } }
            public static string legal { get { return $"{(char)0xf0e3}"; } }
            public static string gavel { get { return $"{(char)0xf0e3}"; } }
            public static string dashboard { get { return $"{(char)0xf0e4}"; } }
            public static string tachometer { get { return $"{(char)0xf0e4}"; } }
            public static string comment_o { get { return $"{(char)0xf0e5}"; } }
            public static string comments_o { get { return $"{(char)0xf0e6}"; } }
            public static string flash { get { return $"{(char)0xf0e7}"; } }
            public static string bolt { get { return $"{(char)0xf0e7}"; } }
            public static string sitemap { get { return $"{(char)0xf0e8}"; } }
            public static string umbrella { get { return $"{(char)0xf0e9}"; } }
            public static string paste { get { return $"{(char)0xf0ea}"; } }
            public static string clipboard { get { return $"{(char)0xf0ea}"; } }
            public static string lightbulb_o { get { return $"{(char)0xf0eb}"; } }
            public static string exchange { get { return $"{(char)0xf0ec}"; } }
            public static string cloud_download { get { return $"{(char)0xf0ed}"; } }
            public static string cloud_upload { get { return $"{(char)0xf0ee}"; } }
            public static string user_md { get { return $"{(char)0xf0f0}"; } }
            public static string stethoscope { get { return $"{(char)0xf0f1}"; } }
            public static string suitcase { get { return $"{(char)0xf0f2}"; } }
            public static string bell_o { get { return $"{(char)0xf0a2}"; } }
            public static string coffee { get { return $"{(char)0xf0f4}"; } }
            public static string cutlery { get { return $"{(char)0xf0f5}"; } }
            public static string file_text_o { get { return $"{(char)0xf0f6}"; } }
            public static string building_o { get { return $"{(char)0xf0f7}"; } }
            public static string hospital_o { get { return $"{(char)0xf0f8}"; } }
            public static string ambulance { get { return $"{(char)0xf0f9}"; } }
            public static string medkit { get { return $"{(char)0xf0fa}"; } }
            public static string fighter_jet { get { return $"{(char)0xf0fb}"; } }
            public static string beer { get { return $"{(char)0xf0fc}"; } }
            public static string h_square { get { return $"{(char)0xf0fd}"; } }
            public static string plus_square { get { return $"{(char)0xf0fe}"; } }
            public static string angle_double_left { get { return $"{(char)0xf100}"; } }
            public static string angle_double_right { get { return $"{(char)0xf101}"; } }
            public static string angle_double_up { get { return $"{(char)0xf102}"; } }
            public static string angle_double_down { get { return $"{(char)0xf103}"; } }
            public static string angle_left { get { return $"{(char)0xf104}"; } }
            public static string angle_right { get { return $"{(char)0xf105}"; } }
            public static string angle_up { get { return $"{(char)0xf106}"; } }
            public static string angle_down { get { return $"{(char)0xf107}"; } }
            public static string desktop { get { return $"{(char)0xf108}"; } }
            public static string laptop { get { return $"{(char)0xf109}"; } }
            public static string tablet { get { return $"{(char)0xf10a}"; } }
            public static string mobile_phone { get { return $"{(char)0xf10b}"; } }
            public static string mobile { get { return $"{(char)0xf10b}"; } }
            public static string circle_o { get { return $"{(char)0xf10c}"; } }
            public static string quote_left { get { return $"{(char)0xf10d}"; } }
            public static string quote_right { get { return $"{(char)0xf10e}"; } }
            public static string spinner { get { return $"{(char)0xf110}"; } }
            public static string circle { get { return $"{(char)0xf111}"; } }
            public static string mail_reply { get { return $"{(char)0xf112}"; } }
            public static string reply { get { return $"{(char)0xf112}"; } }
            public static string github_alt { get { return $"{(char)0xf113}"; } }
            public static string folder_o { get { return $"{(char)0xf114}"; } }
            public static string folder_open_o { get { return $"{(char)0xf115}"; } }
            public static string smile_o { get { return $"{(char)0xf118}"; } }
            public static string frown_o { get { return $"{(char)0xf119}"; } }
            public static string meh_o { get { return $"{(char)0xf11a}"; } }
            public static string gamepad { get { return $"{(char)0xf11b}"; } }
            public static string keyboard_o { get { return $"{(char)0xf11c}"; } }
            public static string flag_o { get { return $"{(char)0xf11d}"; } }
            public static string flag_checkered { get { return $"{(char)0xf11e}"; } }
            public static string terminal { get { return $"{(char)0xf120}"; } }
            public static string code { get { return $"{(char)0xf121}"; } }
            public static string mail_reply_all { get { return $"{(char)0xf122}"; } }
            public static string reply_all { get { return $"{(char)0xf122}"; } }
            public static string star_half_empty { get { return $"{(char)0xf123}"; } }
            public static string star_half_full { get { return $"{(char)0xf123}"; } }
            public static string star_half_o { get { return $"{(char)0xf123}"; } }
            public static string location_arrow { get { return $"{(char)0xf124}"; } }
            public static string crop { get { return $"{(char)0xf125}"; } }
            public static string code_fork { get { return $"{(char)0xf126}"; } }
            public static string unlink { get { return $"{(char)0xf127}"; } }
            public static string chain_broken { get { return $"{(char)0xf127}"; } }
            public static string question { get { return $"{(char)0xf128}"; } }
            public static string info { get { return $"{(char)0xf129}"; } }
            public static string exclamation { get { return $"{(char)0xf12a}"; } }
            public static string superscript { get { return $"{(char)0xf12b}"; } }
            public static string subscript { get { return $"{(char)0xf12c}"; } }
            public static string eraser { get { return $"{(char)0xf12d}"; } }
            public static string puzzle_piece { get { return $"{(char)0xf12e}"; } }
            public static string microphone { get { return $"{(char)0xf130}"; } }
            public static string microphone_slash { get { return $"{(char)0xf131}"; } }
            public static string shield { get { return $"{(char)0xf132}"; } }
            public static string calendar_o { get { return $"{(char)0xf133}"; } }
            public static string fire_extinguisher { get { return $"{(char)0xf134}"; } }
            public static string rocket { get { return $"{(char)0xf135}"; } }
            public static string maxcdn { get { return $"{(char)0xf136}"; } }
            public static string chevron_circle_left { get { return $"{(char)0xf137}"; } }
            public static string chevron_circle_right { get { return $"{(char)0xf138}"; } }
            public static string chevron_circle_up { get { return $"{(char)0xf139}"; } }
            public static string chevron_circle_down { get { return $"{(char)0xf13a}"; } }
            public static string html5 { get { return $"{(char)0xf13b}"; } }
            public static string css3 { get { return $"{(char)0xf13c}"; } }
            public static string anchor { get { return $"{(char)0xf13d}"; } }
            public static string unlock_alt { get { return $"{(char)0xf13e}"; } }
            public static string bullseye { get { return $"{(char)0xf140}"; } }
            public static string ellipsis_h { get { return $"{(char)0xf141}"; } }
            public static string ellipsis_v { get { return $"{(char)0xf142}"; } }
            public static string rss_square { get { return $"{(char)0xf143}"; } }
            public static string play_circle { get { return $"{(char)0xf144}"; } }
            public static string ticket { get { return $"{(char)0xf145}"; } }
            public static string minus_square { get { return $"{(char)0xf146}"; } }
            public static string minus_square_o { get { return $"{(char)0xf147}"; } }
            public static string level_up { get { return $"{(char)0xf148}"; } }
            public static string level_down { get { return $"{(char)0xf149}"; } }
            public static string check_square { get { return $"{(char)0xf14a}"; } }
            public static string pencil_square { get { return $"{(char)0xf14b}"; } }
            public static string external_link_square { get { return $"{(char)0xf14c}"; } }
            public static string share_square { get { return $"{(char)0xf14d}"; } }
            public static string compass { get { return $"{(char)0xf14e}"; } }
            public static string toggle_down { get { return $"{(char)0xf150}"; } }
            public static string caret_square_o_down { get { return $"{(char)0xf150}"; } }
            public static string toggle_up { get { return $"{(char)0xf151}"; } }
            public static string caret_square_o_up { get { return $"{(char)0xf151}"; } }
            public static string toggle_right { get { return $"{(char)0xf152}"; } }
            public static string caret_square_o_right { get { return $"{(char)0xf152}"; } }
            public static string euro { get { return $"{(char)0xf153}"; } }
            public static string eur { get { return $"{(char)0xf153}"; } }
            public static string gbp { get { return $"{(char)0xf154}"; } }
            public static string dollar { get { return $"{(char)0xf155}"; } }
            public static string usd { get { return $"{(char)0xf155}"; } }
            public static string rupee { get { return $"{(char)0xf156}"; } }
            public static string inr { get { return $"{(char)0xf156}"; } }
            public static string cny { get { return $"{(char)0xf157}"; } }
            public static string rmb { get { return $"{(char)0xf157}"; } }
            public static string yen { get { return $"{(char)0xf157}"; } }
            public static string jpy { get { return $"{(char)0xf157}"; } }
            public static string ruble { get { return $"{(char)0xf158}"; } }
            public static string rouble { get { return $"{(char)0xf158}"; } }
            public static string rub { get { return $"{(char)0xf158}"; } }
            public static string won { get { return $"{(char)0xf159}"; } }
            public static string krw { get { return $"{(char)0xf159}"; } }
            public static string bitcoin { get { return $"{(char)0xf15a}"; } }
            public static string btc { get { return $"{(char)0xf15a}"; } }
            public static string file { get { return $"{(char)0xf15b}"; } }
            public static string file_text { get { return $"{(char)0xf15c}"; } }
            public static string sort_alpha_asc { get { return $"{(char)0xf15d}"; } }
            public static string sort_alpha_desc { get { return $"{(char)0xf15e}"; } }
            public static string sort_amount_asc { get { return $"{(char)0xf160}"; } }
            public static string sort_amount_desc { get { return $"{(char)0xf161}"; } }
            public static string sort_numeric_asc { get { return $"{(char)0xf162}"; } }
            public static string sort_numeric_desc { get { return $"{(char)0xf163}"; } }
            public static string thumbs_up { get { return $"{(char)0xf164}"; } }
            public static string thumbs_down { get { return $"{(char)0xf165}"; } }
            public static string youtube_square { get { return $"{(char)0xf166}"; } }
            public static string youtube { get { return $"{(char)0xf167}"; } }
            public static string xing { get { return $"{(char)0xf168}"; } }
            public static string xing_square { get { return $"{(char)0xf169}"; } }
            public static string youtube_play { get { return $"{(char)0xf16a}"; } }
            public static string dropbox { get { return $"{(char)0xf16b}"; } }
            public static string stack_overflow { get { return $"{(char)0xf16c}"; } }
            public static string instagram { get { return $"{(char)0xf16d}"; } }
            public static string flickr { get { return $"{(char)0xf16e}"; } }
            public static string adn { get { return $"{(char)0xf170}"; } }
            public static string bitbucket { get { return $"{(char)0xf171}"; } }
            public static string bitbucket_square { get { return $"{(char)0xf172}"; } }
            public static string tumblr { get { return $"{(char)0xf173}"; } }
            public static string tumblr_square { get { return $"{(char)0xf174}"; } }
            public static string long_arrow_down { get { return $"{(char)0xf175}"; } }
            public static string long_arrow_up { get { return $"{(char)0xf176}"; } }
            public static string long_arrow_left { get { return $"{(char)0xf177}"; } }
            public static string long_arrow_right { get { return $"{(char)0xf178}"; } }
            public static string apple { get { return $"{(char)0xf179}"; } }
            public static string windows { get { return $"{(char)0xf17a}"; } }
            public static string android { get { return $"{(char)0xf17b}"; } }
            public static string linux { get { return $"{(char)0xf17c}"; } }
            public static string dribbble { get { return $"{(char)0xf17d}"; } }
            public static string skype { get { return $"{(char)0xf17e}"; } }
            public static string foursquare { get { return $"{(char)0xf180}"; } }
            public static string trello { get { return $"{(char)0xf181}"; } }
            public static string female { get { return $"{(char)0xf182}"; } }
            public static string male { get { return $"{(char)0xf183}"; } }
            public static string gittip { get { return $"{(char)0xf184}"; } }
            public static string gratipay { get { return $"{(char)0xf184}"; } }
            public static string sun_o { get { return $"{(char)0xf185}"; } }
            public static string moon_o { get { return $"{(char)0xf186}"; } }
            public static string archive { get { return $"{(char)0xf187}"; } }
            public static string bug { get { return $"{(char)0xf188}"; } }
            public static string vk { get { return $"{(char)0xf189}"; } }
            public static string weibo { get { return $"{(char)0xf18a}"; } }
            public static string renren { get { return $"{(char)0xf18b}"; } }
            public static string pagelines { get { return $"{(char)0xf18c}"; } }
            public static string stack_exchange { get { return $"{(char)0xf18d}"; } }
            public static string arrow_circle_o_right { get { return $"{(char)0xf18e}"; } }
            public static string arrow_circle_o_left { get { return $"{(char)0xf190}"; } }
            public static string toggle_left { get { return $"{(char)0xf191}"; } }
            public static string caret_square_o_left { get { return $"{(char)0xf191}"; } }
            public static string dot_circle_o { get { return $"{(char)0xf192}"; } }
            public static string wheelchair { get { return $"{(char)0xf193}"; } }
            public static string vimeo_square { get { return $"{(char)0xf194}"; } }
            public static string turkish_lira { get { return $"{(char)0xf195}"; } }
            public static string @try { get { return $"{(char)0xf195}"; } }
            public static string plus_square_o { get { return $"{(char)0xf196}"; } }
            public static string space_shuttle { get { return $"{(char)0xf197}"; } }
            public static string slack { get { return $"{(char)0xf198}"; } }
            public static string envelope_square { get { return $"{(char)0xf199}"; } }
            public static string wordpress { get { return $"{(char)0xf19a}"; } }
            public static string openid { get { return $"{(char)0xf19b}"; } }
            public static string institution { get { return $"{(char)0xf19c}"; } }
            public static string bank { get { return $"{(char)0xf19c}"; } }
            public static string university { get { return $"{(char)0xf19c}"; } }
            public static string mortar_board { get { return $"{(char)0xf19d}"; } }
            public static string graduation_cap { get { return $"{(char)0xf19d}"; } }
            public static string yahoo { get { return $"{(char)0xf19e}"; } }
            public static string google { get { return $"{(char)0xf1a0}"; } }
            public static string reddit { get { return $"{(char)0xf1a1}"; } }
            public static string reddit_square { get { return $"{(char)0xf1a2}"; } }
            public static string stumbleupon_circle { get { return $"{(char)0xf1a3}"; } }
            public static string stumbleupon { get { return $"{(char)0xf1a4}"; } }
            public static string delicious { get { return $"{(char)0xf1a5}"; } }
            public static string digg { get { return $"{(char)0xf1a6}"; } }
            public static string pied_piper { get { return $"{(char)0xf1a7}"; } }
            public static string pied_piper_alt { get { return $"{(char)0xf1a8}"; } }
            public static string drupal { get { return $"{(char)0xf1a9}"; } }
            public static string joomla { get { return $"{(char)0xf1aa}"; } }
            public static string language { get { return $"{(char)0xf1ab}"; } }
            public static string fax { get { return $"{(char)0xf1ac}"; } }
            public static string building { get { return $"{(char)0xf1ad}"; } }
            public static string child { get { return $"{(char)0xf1ae}"; } }
            public static string paw { get { return $"{(char)0xf1b0}"; } }
            public static string spoon { get { return $"{(char)0xf1b1}"; } }
            public static string cube { get { return $"{(char)0xf1b2}"; } }
            public static string cubes { get { return $"{(char)0xf1b3}"; } }
            public static string behance { get { return $"{(char)0xf1b4}"; } }
            public static string behance_square { get { return $"{(char)0xf1b5}"; } }
            public static string steam { get { return $"{(char)0xf1b6}"; } }
            public static string steam_square { get { return $"{(char)0xf1b7}"; } }
            public static string recycle { get { return $"{(char)0xf1b8}"; } }
            public static string automobile { get { return $"{(char)0xf1b9}"; } }
            public static string car { get { return $"{(char)0xf1b9}"; } }
            public static string cab { get { return $"{(char)0xf1ba}"; } }
            public static string taxi { get { return $"{(char)0xf1ba}"; } }
            public static string tree { get { return $"{(char)0xf1bb}"; } }
            public static string spotify { get { return $"{(char)0xf1bc}"; } }
            public static string deviantart { get { return $"{(char)0xf1bd}"; } }
            public static string soundcloud { get { return $"{(char)0xf1be}"; } }
            public static string database { get { return $"{(char)0xf1c0}"; } }
            public static string file_pdf_o { get { return $"{(char)0xf1c1}"; } }
            public static string file_word_o { get { return $"{(char)0xf1c2}"; } }
            public static string file_excel_o { get { return $"{(char)0xf1c3}"; } }
            public static string file_powerpoint_o { get { return $"{(char)0xf1c4}"; } }
            public static string file_photo_o { get { return $"{(char)0xf1c5}"; } }
            public static string file_picture_o { get { return $"{(char)0xf1c5}"; } }
            public static string file_image_o { get { return $"{(char)0xf1c5}"; } }
            public static string file_zip_o { get { return $"{(char)0xf1c6}"; } }
            public static string file_archive_o { get { return $"{(char)0xf1c6}"; } }
            public static string file_sound_o { get { return $"{(char)0xf1c7}"; } }
            public static string file_audio_o { get { return $"{(char)0xf1c7}"; } }
            public static string file_movie_o { get { return $"{(char)0xf1c8}"; } }
            public static string file_video_o { get { return $"{(char)0xf1c8}"; } }
            public static string file_code_o { get { return $"{(char)0xf1c9}"; } }
            public static string vine { get { return $"{(char)0xf1ca}"; } }
            public static string codepen { get { return $"{(char)0xf1cb}"; } }
            public static string jsfiddle { get { return $"{(char)0xf1cc}"; } }
            public static string life_bouy { get { return $"{(char)0xf1cd}"; } }
            public static string life_buoy { get { return $"{(char)0xf1cd}"; } }
            public static string life_saver { get { return $"{(char)0xf1cd}"; } }
            public static string support { get { return $"{(char)0xf1cd}"; } }
            public static string life_ring { get { return $"{(char)0xf1cd}"; } }
            public static string circle_o_notch { get { return $"{(char)0xf1ce}"; } }
            public static string ra { get { return $"{(char)0xf1d0}"; } }
            public static string rebel { get { return $"{(char)0xf1d0}"; } }
            public static string ge { get { return $"{(char)0xf1d1}"; } }
            public static string empire { get { return $"{(char)0xf1d1}"; } }
            public static string git_square { get { return $"{(char)0xf1d2}"; } }
            public static string git { get { return $"{(char)0xf1d3}"; } }
            public static string y_combinator_square { get { return $"{(char)0xf1d4}"; } }
            public static string yc_square { get { return $"{(char)0xf1d4}"; } }
            public static string hacker_news { get { return $"{(char)0xf1d4}"; } }
            public static string tencent_weibo { get { return $"{(char)0xf1d5}"; } }
            public static string qq { get { return $"{(char)0xf1d6}"; } }
            public static string wechat { get { return $"{(char)0xf1d7}"; } }
            public static string weixin { get { return $"{(char)0xf1d7}"; } }
            public static string send { get { return $"{(char)0xf1d8}"; } }
            public static string paper_plane { get { return $"{(char)0xf1d8}"; } }
            public static string send_o { get { return $"{(char)0xf1d9}"; } }
            public static string paper_plane_o { get { return $"{(char)0xf1d9}"; } }
            public static string history { get { return $"{(char)0xf1da}"; } }
            public static string circle_thin { get { return $"{(char)0xf1db}"; } }
            public static string header { get { return $"{(char)0xf1dc}"; } }
            public static string paragraph { get { return $"{(char)0xf1dd}"; } }
            public static string sliders { get { return $"{(char)0xf1de}"; } }
            public static string share_alt { get { return $"{(char)0xf1e0}"; } }
            public static string share_alt_square { get { return $"{(char)0xf1e1}"; } }
            public static string bomb { get { return $"{(char)0xf1e2}"; } }
            public static string soccer_ball_o { get { return $"{(char)0xf1e3}"; } }
            public static string futbol_o { get { return $"{(char)0xf1e3}"; } }
            public static string tty { get { return $"{(char)0xf1e4}"; } }
            public static string binoculars { get { return $"{(char)0xf1e5}"; } }
            public static string plug { get { return $"{(char)0xf1e6}"; } }
            public static string slideshare { get { return $"{(char)0xf1e7}"; } }
            public static string twitch { get { return $"{(char)0xf1e8}"; } }
            public static string yelp { get { return $"{(char)0xf1e9}"; } }
            public static string newspaper_o { get { return $"{(char)0xf1ea}"; } }
            public static string wifi { get { return $"{(char)0xf1eb}"; } }
            public static string calculator { get { return $"{(char)0xf1ec}"; } }
            public static string paypal { get { return $"{(char)0xf1ed}"; } }
            public static string google_wallet { get { return $"{(char)0xf1ee}"; } }
            public static string cc_visa { get { return $"{(char)0xf1f0}"; } }
            public static string cc_mastercard { get { return $"{(char)0xf1f1}"; } }
            public static string cc_discover { get { return $"{(char)0xf1f2}"; } }
            public static string cc_amex { get { return $"{(char)0xf1f3}"; } }
            public static string cc_paypal { get { return $"{(char)0xf1f4}"; } }
            public static string cc_stripe { get { return $"{(char)0xf1f5}"; } }
            public static string bell_slash { get { return $"{(char)0xf1f6}"; } }
            public static string bell_slash_o { get { return $"{(char)0xf1f7}"; } }
            public static string trash { get { return $"{(char)0xf1f8}"; } }
            public static string copyright { get { return $"{(char)0xf1f9}"; } }
            public static string at { get { return $"{(char)0xf1fa}"; } }
            public static string eyedropper { get { return $"{(char)0xf1fb}"; } }
            public static string paint_brush { get { return $"{(char)0xf1fc}"; } }
            public static string birthday_cake { get { return $"{(char)0xf1fd}"; } }
            public static string area_chart { get { return $"{(char)0xf1fe}"; } }
            public static string pie_chart { get { return $"{(char)0xf200}"; } }
            public static string line_chart { get { return $"{(char)0xf201}"; } }
            public static string lastfm { get { return $"{(char)0xf202}"; } }
            public static string lastfm_square { get { return $"{(char)0xf203}"; } }
            public static string toggle_off { get { return $"{(char)0xf204}"; } }
            public static string toggle_on { get { return $"{(char)0xf205}"; } }
            public static string bicycle { get { return $"{(char)0xf206}"; } }
            public static string bus { get { return $"{(char)0xf207}"; } }
            public static string ioxhost { get { return $"{(char)0xf208}"; } }
            public static string angellist { get { return $"{(char)0xf209}"; } }
            public static string cc { get { return $"{(char)0xf20a}"; } }
            public static string shekel { get { return $"{(char)0xf20b}"; } }
            public static string sheqel { get { return $"{(char)0xf20b}"; } }
            public static string ils { get { return $"{(char)0xf20b}"; } }
            public static string meanpath { get { return $"{(char)0xf20c}"; } }
            public static string buysellads { get { return $"{(char)0xf20d}"; } }
            public static string connectdevelop { get { return $"{(char)0xf20e}"; } }
            public static string dashcube { get { return $"{(char)0xf210}"; } }
            public static string forumbee { get { return $"{(char)0xf211}"; } }
            public static string leanpub { get { return $"{(char)0xf212}"; } }
            public static string sellsy { get { return $"{(char)0xf213}"; } }
            public static string shirtsinbulk { get { return $"{(char)0xf214}"; } }
            public static string simplybuilt { get { return $"{(char)0xf215}"; } }
            public static string skyatlas { get { return $"{(char)0xf216}"; } }
            public static string cart_plus { get { return $"{(char)0xf217}"; } }
            public static string cart_arrow_down { get { return $"{(char)0xf218}"; } }
            public static string diamond { get { return $"{(char)0xf219}"; } }
            public static string ship { get { return $"{(char)0xf21a}"; } }
            public static string user_secret { get { return $"{(char)0xf21b}"; } }
            public static string motorcycle { get { return $"{(char)0xf21c}"; } }
            public static string street_view { get { return $"{(char)0xf21d}"; } }
            public static string heartbeat { get { return $"{(char)0xf21e}"; } }
            public static string venus { get { return $"{(char)0xf221}"; } }
            public static string mars { get { return $"{(char)0xf222}"; } }
            public static string mercury { get { return $"{(char)0xf223}"; } }
            public static string intersex { get { return $"{(char)0xf224}"; } }
            public static string transgender { get { return $"{(char)0xf224}"; } }
            public static string transgender_alt { get { return $"{(char)0xf225}"; } }
            public static string venus_double { get { return $"{(char)0xf226}"; } }
            public static string mars_double { get { return $"{(char)0xf227}"; } }
            public static string venus_mars { get { return $"{(char)0xf228}"; } }
            public static string mars_stroke { get { return $"{(char)0xf229}"; } }
            public static string mars_stroke_v { get { return $"{(char)0xf22a}"; } }
            public static string mars_stroke_h { get { return $"{(char)0xf22b}"; } }
            public static string neuter { get { return $"{(char)0xf22c}"; } }
            public static string genderless { get { return $"{(char)0xf22d}"; } }
            public static string facebook_official { get { return $"{(char)0xf230}"; } }
            public static string pinterest_p { get { return $"{(char)0xf231}"; } }
            public static string whatsapp { get { return $"{(char)0xf232}"; } }
            public static string server { get { return $"{(char)0xf233}"; } }
            public static string user_plus { get { return $"{(char)0xf234}"; } }
            public static string user_times { get { return $"{(char)0xf235}"; } }
            public static string hotel { get { return $"{(char)0xf236}"; } }
            public static string bed { get { return $"{(char)0xf236}"; } }
            public static string viacoin { get { return $"{(char)0xf237}"; } }
            public static string train { get { return $"{(char)0xf238}"; } }
            public static string subway { get { return $"{(char)0xf239}"; } }
            public static string medium { get { return $"{(char)0xf23a}"; } }
            public static string yc { get { return $"{(char)0xf23b}"; } }
            public static string y_combinator { get { return $"{(char)0xf23b}"; } }
            public static string optin_monster { get { return $"{(char)0xf23c}"; } }
            public static string opencart { get { return $"{(char)0xf23d}"; } }
            public static string expeditedssl { get { return $"{(char)0xf23e}"; } }
            public static string battery_4 { get { return $"{(char)0xf240}"; } }
            public static string battery_full { get { return $"{(char)0xf240}"; } }
            public static string battery_3 { get { return $"{(char)0xf241}"; } }
            public static string battery_three_quarters { get { return $"{(char)0xf241}"; } }
            public static string battery_2 { get { return $"{(char)0xf242}"; } }
            public static string battery_half { get { return $"{(char)0xf242}"; } }
            public static string battery_1 { get { return $"{(char)0xf243}"; } }
            public static string battery_quarter { get { return $"{(char)0xf243}"; } }
            public static string battery_0 { get { return $"{(char)0xf244}"; } }
            public static string battery_empty { get { return $"{(char)0xf244}"; } }
            public static string mouse_pointer { get { return $"{(char)0xf245}"; } }
            public static string i_cursor { get { return $"{(char)0xf246}"; } }
            public static string object_group { get { return $"{(char)0xf247}"; } }
            public static string object_ungroup { get { return $"{(char)0xf248}"; } }
            public static string sticky_note { get { return $"{(char)0xf249}"; } }
            public static string sticky_note_o { get { return $"{(char)0xf24a}"; } }
            public static string cc_jcb { get { return $"{(char)0xf24b}"; } }
            public static string cc_diners_club { get { return $"{(char)0xf24c}"; } }
            public static string clone { get { return $"{(char)0xf24d}"; } }
            public static string balance_scale { get { return $"{(char)0xf24e}"; } }
            public static string hourglass_o { get { return $"{(char)0xf250}"; } }
            public static string hourglass_1 { get { return $"{(char)0xf251}"; } }
            public static string hourglass_start { get { return $"{(char)0xf251}"; } }
            public static string hourglass_2 { get { return $"{(char)0xf252}"; } }
            public static string hourglass_half { get { return $"{(char)0xf252}"; } }
            public static string hourglass_3 { get { return $"{(char)0xf253}"; } }
            public static string hourglass_end { get { return $"{(char)0xf253}"; } }
            public static string hourglass { get { return $"{(char)0xf254}"; } }
            public static string hand_grab_o { get { return $"{(char)0xf255}"; } }
            public static string hand_rock_o { get { return $"{(char)0xf255}"; } }
            public static string hand_stop_o { get { return $"{(char)0xf256}"; } }
            public static string hand_paper_o { get { return $"{(char)0xf256}"; } }
            public static string hand_scissors_o { get { return $"{(char)0xf257}"; } }
            public static string hand_lizard_o { get { return $"{(char)0xf258}"; } }
            public static string hand_spock_o { get { return $"{(char)0xf259}"; } }
            public static string hand_pointer_o { get { return $"{(char)0xf25a}"; } }
            public static string hand_peace_o { get { return $"{(char)0xf25b}"; } }
            public static string trademark { get { return $"{(char)0xf25c}"; } }
            public static string registered { get { return $"{(char)0xf25d}"; } }
            public static string creative_commons { get { return $"{(char)0xf25e}"; } }
            public static string gg { get { return $"{(char)0xf260}"; } }
            public static string gg_circle { get { return $"{(char)0xf261}"; } }
            public static string tripadvisor { get { return $"{(char)0xf262}"; } }
            public static string odnoklassniki { get { return $"{(char)0xf263}"; } }
            public static string odnoklassniki_square { get { return $"{(char)0xf264}"; } }
            public static string get_pocket { get { return $"{(char)0xf265}"; } }
            public static string wikipedia_w { get { return $"{(char)0xf266}"; } }
            public static string safari { get { return $"{(char)0xf267}"; } }
            public static string chrome { get { return $"{(char)0xf268}"; } }
            public static string firefox { get { return $"{(char)0xf269}"; } }
            public static string opera { get { return $"{(char)0xf26a}"; } }
            public static string internet_explorer { get { return $"{(char)0xf26b}"; } }
            public static string tv { get { return $"{(char)0xf26c}"; } }
            public static string television { get { return $"{(char)0xf26c}"; } }
            public static string contao { get { return $"{(char)0xf26d}"; } }
            public static string _500px { get { return $"{(char)0xf26e}"; } }
            public static string amazon { get { return $"{(char)0xf270}"; } }
            public static string calendar_plus_o { get { return $"{(char)0xf271}"; } }
            public static string calendar_minus_o { get { return $"{(char)0xf272}"; } }
            public static string calendar_times_o { get { return $"{(char)0xf273}"; } }
            public static string calendar_check_o { get { return $"{(char)0xf274}"; } }
            public static string industry { get { return $"{(char)0xf275}"; } }
            public static string map_pin { get { return $"{(char)0xf276}"; } }
            public static string map_signs { get { return $"{(char)0xf277}"; } }
            public static string map_o { get { return $"{(char)0xf278}"; } }
            public static string map { get { return $"{(char)0xf279}"; } }
            public static string commenting { get { return $"{(char)0xf27a}"; } }
            public static string commenting_o { get { return $"{(char)0xf27b}"; } }
            public static string houzz { get { return $"{(char)0xf27c}"; } }
            public static string vimeo { get { return $"{(char)0xf27d}"; } }
            public static string black_tie { get { return $"{(char)0xf27e}"; } }
            public static string fonticons { get { return $"{(char)0xf280}"; } }
        }
    }
}
